---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - koroner.pez.sh
  resources:
  - koronerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - koroner.pez.sh
  resources:
  - obituaries
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - koroner.pez.sh
  resources:
  - obituaries/status
  verbs:
  - get
  - patch
  - update
