apiVersion: v2
name: koroner-chart
description: Koroner operator - performs post-mortems on failed workloads
type: application
version: 0.1.1
appVersion: "1.0.2"
home: https://github.com/RWejlgaard/koroner
sources:
  - https://github.com/RWejlgaard/koroner
maintainers:
  - name: RWejlgaard
keywords:
  - kubernetes
  - operator
  - observability
  - post-mortem
