//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventRecord) DeepCopyInto(out *EventRecord) {
	*out = *in
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventRecord.
func (in *EventRecord) DeepCopy() *EventRecord {
	if in == nil {
		return nil
	}
	out := new(EventRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KoronerConfig) DeepCopyInto(out *KoronerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KoronerConfig.
func (in *KoronerConfig) DeepCopy() *KoronerConfig {
	if in == nil {
		return nil
	}
	out := new(KoronerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KoronerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KoronerConfigList) DeepCopyInto(out *KoronerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KoronerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KoronerConfigList.
func (in *KoronerConfigList) DeepCopy() *KoronerConfigList {
	if in == nil {
		return nil
	}
	out := new(KoronerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KoronerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KoronerConfigSpec) DeepCopyInto(out *KoronerConfigSpec) {
	*out = *in
	in.Watch.DeepCopyInto(&out.Watch)
	if in.RestartThreshold != nil {
		in, out := &in.RestartThreshold, &out.RestartThreshold
		*out = new(int32)
		**out = **in
	}
	if in.LogTailLines != nil {
		in, out := &in.LogTailLines, &out.LogTailLines
		*out = new(int32)
		**out = **in
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ObituaryRetention != nil {
		in, out := &in.ObituaryRetention, &out.ObituaryRetention
		*out = new(v1.Duration)
		**out = **in
	}
	in.Prometheus.DeepCopyInto(&out.Prometheus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KoronerConfigSpec.
func (in *KoronerConfigSpec) DeepCopy() *KoronerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KoronerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KoronerConfigStatus) DeepCopyInto(out *KoronerConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KoronerConfigStatus.
func (in *KoronerConfigStatus) DeepCopy() *KoronerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KoronerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSnapshot) DeepCopyInto(out *MetricsSnapshot) {
	*out = *in
	if in.Samples != nil {
		in, out := &in.Samples, &out.Samples
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSnapshot.
func (in *MetricsSnapshot) DeepCopy() *MetricsSnapshot {
	if in == nil {
		return nil
	}
	out := new(MetricsSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Obituary) DeepCopyInto(out *Obituary) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Obituary.
func (in *Obituary) DeepCopy() *Obituary {
	if in == nil {
		return nil
	}
	out := new(Obituary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Obituary) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObituaryList) DeepCopyInto(out *ObituaryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Obituary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObituaryList.
func (in *ObituaryList) DeepCopy() *ObituaryList {
	if in == nil {
		return nil
	}
	out := new(ObituaryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObituaryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObituarySpec) DeepCopyInto(out *ObituarySpec) {
	*out = *in
	out.Subject = in.Subject
	if in.TimeOfDeath != nil {
		in, out := &in.TimeOfDeath, &out.TimeOfDeath
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObituarySpec.
func (in *ObituarySpec) DeepCopy() *ObituarySpec {
	if in == nil {
		return nil
	}
	out := new(ObituarySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObituaryStatus) DeepCopyInto(out *ObituaryStatus) {
	*out = *in
	if in.FirstSeen != nil {
		in, out := &in.FirstSeen, &out.FirstSeen
		*out = (*in).DeepCopy()
	}
	if in.LastSeen != nil {
		in, out := &in.LastSeen, &out.LastSeen
		*out = (*in).DeepCopy()
	}
	if in.ExitCode != nil {
		in, out := &in.ExitCode, &out.ExitCode
		*out = new(int32)
		**out = **in
	}
	if in.Signal != nil {
		in, out := &in.Signal, &out.Signal
		*out = new(int32)
		**out = **in
	}
	if in.EventTimeline != nil {
		in, out := &in.EventTimeline, &out.EventTimeline
		*out = make([]EventRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = make([]OwnerRecord, len(*in))
		copy(*out, *in)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricsSnapshot)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObituaryStatus.
func (in *ObituaryStatus) DeepCopy() *ObituaryStatus {
	if in == nil {
		return nil
	}
	out := new(ObituaryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnerRecord) DeepCopyInto(out *OwnerRecord) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnerRecord.
func (in *OwnerRecord) DeepCopy() *OwnerRecord {
	if in == nil {
		return nil
	}
	out := new(OwnerRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusPolicy) DeepCopyInto(out *PrometheusPolicy) {
	*out = *in
	if in.Queries != nil {
		in, out := &in.Queries, &out.Queries
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusPolicy.
func (in *PrometheusPolicy) DeepCopy() *PrometheusPolicy {
	if in == nil {
		return nil
	}
	out := new(PrometheusPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subject) DeepCopyInto(out *Subject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subject.
func (in *Subject) DeepCopy() *Subject {
	if in == nil {
		return nil
	}
	out := new(Subject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchPolicy) DeepCopyInto(out *WatchPolicy) {
	*out = *in
	if in.PodCrashes != nil {
		in, out := &in.PodCrashes, &out.PodCrashes
		*out = new(bool)
		**out = **in
	}
	if in.JobFailures != nil {
		in, out := &in.JobFailures, &out.JobFailures
		*out = new(bool)
		**out = **in
	}
	if in.RolloutFailures != nil {
		in, out := &in.RolloutFailures, &out.RolloutFailures
		*out = new(bool)
		**out = **in
	}
	if in.Evictions != nil {
		in, out := &in.Evictions, &out.Evictions
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchPolicy.
func (in *WatchPolicy) DeepCopy() *WatchPolicy {
	if in == nil {
		return nil
	}
	out := new(WatchPolicy)
	in.DeepCopyInto(out)
	return out
}
